spring:
  datasource:
    url: jdbc:sqlserver://azure-stocknotifier.database.windows.net:1433;database=db-stocknotifier;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: ${STOCKNOTIFIER_DB_ADMIN_USERNAME}@azure-stocknotifier
    password: ${STOCKNOTIFIER_DB_ADMIN_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      # Azure SQL specific settings
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2016Dialect
        connection.provider_disables_autocommit: true
        # Azure SQL specific properties
        jdbc.lob.non_contextual_creation: true
        jdbc.time_zone: UTC

  # Kafka configuration remains the same as previous example
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      stock-prices: stock-prices